version: '3.4'

services:
  ############################
  # Basket service + Dapr sidecar
  ############################
  productapp:
    build:
      context: .
      dockerfile: src/ProductService/ProductService.Api/Dockerfile
    ports:
      - "50001:80"
    depends_on:
      - redis
      - placement
      - zipkin
    networks:
      - dapr-demo
  productapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "productapp",
     "-app-port", "5001",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50001",
     "-components-path", "/components",
     "--config","/components/appconfig.yaml"]
    volumes:
        - "./components/:/components"
    depends_on:
      - productapp
    network_mode: "service:productapp"
  ############################
  # Notification service + Dapr sidecar
  ############################
  notificationapp:
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    depends_on:
      - redis
      - placement
      - zipkin
    networks:
      - dapr-demo
  notificationapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "notificationapp",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components",
     "--config","/components/appconfig.yaml"]
    volumes:
        - "./components/:/components"
    depends_on:
      - notificationapp
    network_mode: "service:notificationapp"
  ############################
  # Order service + Dapr sidecar
  ############################
  orderapp:
    build:
      context: .
      dockerfile: src/OrderService/OrderService.Api/Dockerfile
    ports:
      - "50002:80"
    depends_on:
      - redis
      - placement
      - zipkin
    networks:
      - dapr-demo
  orderapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "orderapp",
     "-app-port", "5002",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components",
     "--config","/components/appconfig.yaml"]
    volumes:
        - "./components/:/components"
    depends_on:
      - orderapp
    network_mode: "service:orderapp"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-demo
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - dapr-demo
  ############################
  # Zipkin
  ############################
  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"
    networks:
      - dapr-demo
networks:
    dapr-demo: