version: '3.4'

services:
  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

