version: '3.4'

services:
  orderservice:
    build:
      context: .
      dockerfile: src/OrderService/OrderService.Api/Dockerfile
    depends_on:
      - redis
      - placement
      - zipkin
      - seq
    networks:
      - darp-sample

  orderservice-dapr:
    image: "daprio/daprd:1.0.0"
    network_mode: "service:orderservice"
    depends_on:
        - orderservice

  productservice:
    build:
      context: .
      dockerfile: src/ProductService/ProductService.Api/Dockerfile
    depends_on:
      - redis
      - placement
      - zipkin
      - seq
    networks:
      - darp-sample

  productservice-dapr:
    image: "daprio/daprd:1.0.0"
    network_mode: "service:productservice"
    depends_on:
        - productservice

  notificationservice:
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    depends_on:
      - redis
      - placement
      - zipkin
      - seq
    networks:
      - darp-sample

  notificationservice-dapr:
    image: "daprio/daprd:1.0.0"
    network_mode: "service:notificationservice"
    depends_on:
        - notificationservice

  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr:1.0.0"
    networks:
      - darp-sample

  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    networks:
      - darp-sample

  ############################
  # Zipkin
  ############################
  zipkin:
    image: "openzipkin/zipkin-slim"
    networks:
      - darp-sample

  ############################
  # Seq
  ############################
  seq:
    image: datalust/seq:latest
    networks:
      - darp-sample

networks:
  darp-sample: