name: dapr-sample

extensions:
- name: dapr
- name: seq

services:
- name: redis
  image: redis:alpine
  bindings:
  - port: 6379
    protocol: http

- name: zipkin
  image: openzipkin/zipkin-slim
  bindings:
  - port: 9411
    protocol: http

- name: orderservice
  project: src/OrderService/OrderService.Api/OrderService.Api.csproj
  bindings:
  - port: 5001
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: Serilog__SeqServerUrl
    value: http://localhost:5341

- name: productservice
  project: src/ProductService/ProductService.Api/ProductService.Api.csproj
  bindings:
  - port: 5002
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: Serilog__SeqServerUrl
    value: http://localhost:5341

- name: notificationservice
  project: src/NotificationService/NotificationService.csproj
  env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: Serilog__SeqServerUrl
    value: http://localhost:5341